# Generated by Django 4.0.5 on 2022-11-13 18:47

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, upload_to=reports.models.user_directory_path),
        ),
    ]
