# Generated by Django 4.0.5 on 2022-11-13 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('name', 'remarks')},
        ),
    ]
