# Generated by Django 4.0.5 on 2022-11-13 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_avatar'),
        ('reports', '0004_alter_report_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('name', 'remarks', 'author')},
        ),
    ]
