# Generated by Django 4.0.5 on 2022-11-12 19:42

from django.db import migrations, models
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='csv_file',
            field=models.FileField(null=True, upload_to=sales.models.user_directory_path),
        ),
    ]
