# Generated by Django 4.0.5 on 2022-11-13 18:47

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='logo',
            field=models.ImageField(default='no_picture.jpeg', upload_to=customers.models.user_directory_path),
        ),
    ]
