# Generated by Django 4.0.5 on 2022-11-13 18:47

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no_image.webp', upload_to=products.models.user_directory_path),
        ),
    ]
