# Generated by Django 4.0.5 on 2022-11-15 15:01

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/no_product_image.png', upload_to=products.models.user_directory_path),
        ),
    ]
