apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-analysis-web-deployment
  labels:
    app: data-analysis-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-analysis-web-deployment
  template:
    metadata:
      labels:
        app: data-analysis-web-deployment
    spec:
      containers:
        - name: data-analysis-web
          image: registry.digitalocean.com/my-do-registry/data-analysis-web:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: data-analysis-web-prod-env
          env:
            - name: PORT
              value: "8002"
          ports:
            - containerPort: 8002
              protocol: TCP
      imagePullSecrets:
        - name: my-do-registry

---
apiVersion: v1
kind: Service
metadata:
  name: data-analysis-web-service
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "d9876ba0-c033-43c3-8513-4ced04c16fdf"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  type: LoadBalancer
  selector:
    app: data-analysis-web-deployment
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8002
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8002
