# Generated by Django 4.0.5 on 2022-11-13 12:30

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='no_picture.png', upload_to=profiles.models.user_directory_path),
        ),
    ]
