name: Build Docker Container & Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_django_job:
    uses: Sai-Santhan/Data-Analysis/.github/workflows/test-django.yaml@main
  docker_build:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    env:
      CLUSTER_NAME: data-analysis-cluster
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
      - name: Login to DO Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
      - name: Build Container image
        working-directory: ./src
        run: |
          docker build -f Dockerfile \
            -t registry.digitalocean.com/my-do-registry/data-analysis-web:latest \
            -t registry.digitalocean.com/my-do-registry/data-analysis-web:${GITHUB_SHA::7} \
            .
      - name: Push Image to DO Container Registry
        run: |
          docker push registry.digitalocean.com/my-do-registry/data-analysis-web --all-tags
      - name: K8s cluster kubeconfig file with short-lived credentials
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}
      - name: Update deployment secrets
        run: |
          cat << EOF >> src/.prod.env
          DEBUG=${{ secrets.DEBUG }}
          DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
          DJANGO_LOGLEVEL=${{ secrets.DJANGO_LOGLEVEL }}
          USE_SPACES=${{ secrets.USE_SPACES }}
          STATIC_ACCESS_KEY_ID=${{ secrets.STATIC_ACCESS_KEY_ID }}
          STATIC_SECRET_ACCESS_KEY=${{ secrets.STATIC_SECRET_ACCESS_KEY }}
          STORAGE_BUCKET_NAME=${{ secrets.STORAGE_BUCKET_NAME }}
          STORAGE_ENDPOINT_URL=${{ secrets.STORAGE_ENDPOINT_URL }}
          DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}
          DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
          DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_SUPERUSER_EMAIL }}
          ENV_ALLOWED_HOST=${{ secrets.ENV_ALLOWED_HOST }}
          ENV_CSRF_TRUSTED_ORIGINS=${{ secrets.ENV_CSRF_TRUSTED_ORIGINS }}
          ENV_CSRF_COOKIE_SECURE=${{ secrets.ENV_CSRF_COOKIE_SECURE }}
          ENV_SESSION_COOKIE_SECURE=${{ secrets.ENV_SESSION_COOKIE_SECURE }}
          ENV_SECURE_BROWSER_XSS_FILTER=${{ secrets.ENV_SECURE_BROWSER_XSS_FILTER }}
          ENV_SECURE_CONTENT_TYPE_NOSNIFF=${{ secrets.ENV_SECURE_CONTENT_TYPE_NOSNIFF }}
          ENV_SECURE_SSL_REDIRECT=${{ secrets.ENV_SECURE_SSL_REDIRECT }}
          ENV_SECURE_HSTS_SECONDS=${{ secrets.ENV_SECURE_HSTS_SECONDS }}
          ENV_SECURE_HSTS_INCLUDE_SUBDOMAINS=${{ secrets.ENV_SECURE_HSTS_INCLUDE_SUBDOMAINS }}
          ENV_SECURE_HSTS_PRELOAD=${{ secrets.ENV_SECURE_HSTS_PRELOAD }}
          DB_IGNORE_SSL=${{ secrets.DB_IGNORE_SSL }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          EOF
          kubectl delete secret data-analysis-web-prod-env
          kubectl create secret generic data-analysis-web-prod-env --from-env-file=src/.prod.env
      - name: Update Deployment image
        run: |
          kubectl set image deployment/data-analysis-web-deployment data-analysis-web=registry.digitalocean.com/my-do-registry/data-analysis-web:${GITHUB_SHA::7}
      - name: Wait for Rollout to finish
        run: |
          kubectl rollout status deployment/data-analysis-web-deployment
      - name: Post-Build Django Commands - Migrate, Collectstatic & Fixtures
        run: |
          export SINGLE_POD_NAME=$(kubectl get pod -l app=data-analysis-web-deployment -o jsonpath="{.items[0].metadata.name}")
          kubectl exec -it $SINGLE_POD_NAME -- bash /app/migrate.sh
          kubectl exec -it $SINGLE_POD_NAME -- bash /app/collectstatic.sh
          kubectl exec -it $SINGLE_POD_NAME -- bash /app/fixtures.sh
