name: Django CI & Postgres Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  django-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    env:
      POSTGRES_DB: defaultdb
      POSTGRES_USER: doadmin
      POSTGRES_PASSWORD: AVNS_f9kbnihLx46r_77d_C4
      POSTGRES_HOST: private-data-analysis-postgresql-db-do-user-12157797-0.b.db.ondigitalocean.com
      POSTGRES_PORT: 25060
    services:
      postgres_main:
        image: postgres:14
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v3
        name: Check out Repository
      - uses: actions/setup-python@v4
        name: Set up Python ${{ matrix.python-version }}
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        name: Install Dependencies
      - run: |
          python manage.py test
        name: Run Tests