name: Application & Database Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  django-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    services:
      postgres_main:
        image: postgres:14
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v3
        name: Check out Repository
      - uses: actions/setup-python@v4
        name: Set up Python ${{ matrix.python-version }}
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        name: Install Dependencies
      - run: |
          python manage.py test
        name: Run Tests